In [47]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

df  = pd.read_excel("../data/Pakistani_Foods_Nutrition_FYP.xlsx")
df1 = pd.read_csv("../data/Foods_data.csv")
df2 = pd.read_csv("../data/Indian_Food_Nutrition_Processed.csv")

In [48]:
df.rename(columns={"Dish Name (Urdu/Common Name)": "Dish Name"}, inplace=True)

In [49]:
df["Dish Name"] =  df["Dish Name"].str.split("(").str.get(0).str.strip().str.split("/").str.get(0).str.strip()

In [50]:
df.head(3)

,Dish Name,Category,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg),Notes / Status
0,Halwa Puri,Breakfast,420,52.0,7.0,20.0,8.0,2.1,380,45,1.8,1.2,18.0,Iconic Pak breakfast – NOT in dataset
1,Nihari,Main Dish,310,8.0,28.0,19.0,0.5,0.8,620,42,3.8,5.0,22.0,NOT in dataset – essential Pak dish
2,Paye,Main Dish,280,4.0,26.0,18.0,0.0,0.2,540,180,2.5,0.0,12.0,NOT in dataset

In [51]:
df1.head(2)

,imgurl,name,course,cusine,keyword,summary,ingredients,nutritions,Times
0,https://recipe52.com/wp-content/uploads/2023/0...,Achari Chicken,Dinner Recipes,"North Indian, Pakistani, Punjabi",Achari Chicken,Authentic Achari Chicken recipe with easy spic...,"['cumin seeds', 'coriander seeds', 'fennel see...","{'Calories': '505 kcal', 'Carbohydrates': '14 ...","{'PrepTime': '10 minutes', 'CookTime': '30 min..."
1,https://recipe52.com/wp-content/uploads/2021/0...,Aloo Chana Chaat,Snack,"Indian, Pakistani","aloo channa chaat, channa chaat","Easy, healthy, extremely versatile Pakistani s...","['cooked chickpea ', 'cubbed potato ', 'cumin ...","{'Calories': '283 kcal', 'Carbohydrates': '52 ...","{'PrepTime': '20 minutes', 'CookTime': '15 min..."

In [52]:
df1["name"] = df1["name"].str.split("Recipe").str.get(0).str.strip().str.split("(").str.get(0).str.strip()   # Dulce De Leche (Boiled Condensed Milk)   # Pakistani Aloo Palak

name_issue = {"Dulce De Leche (Boiled Condensed Milk)":"Boiled Condensed Milk","Pakistani Aloo Palak":"Aloo Palak"}
df1["Dish Name"] = df1["name"].replace(name_issue,inplace=True)

C:\Users\Zainch-032\AppData\Local\Temp\ipykernel_1772\1962221968.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["Dish Name"] = df1["name"].replace(name_issue,inplace=True)

In [53]:
import ast
df1["Calories (kcal)"]  = df1["nutritions"].apply(lambda x: ast.literal_eval(x)["Calories"].replace(" kcal", "").strip())

In [54]:
df1["nutritions"][0]

"{'Calories': '505 kcal', 'Carbohydrates': '14 g', 'Protein': '39 g', 'Fat': '32 g', 'Saturated Fat': '4 g', 'Polyunsaturated Fat': '9 g', 'Monounsaturated Fat': '18 g', 'Trans Fat': '0.1 g', 'Cholesterol': '122 mg', 'Sodium': '571 mg', 'Potassium': '874 mg', 'Fiber': '4 g', 'Sugar': '8 g', 'Vitamin A': '1369 IU', 'Vitamin C': '27 mg', 'Calcium': '124 mg', 'Iron': '3 mg'}"

In [55]:
df1["nutritions"] = df1["nutritions"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

df1["Carbohydrates (g)"] = df1["nutritions"].apply(lambda x: x.get("Carbohydrates", "0").split()[0])
df1["Protein (g)"]       = df1["nutritions"].apply(lambda x: x.get("Protein", "0").split()[0])
df1["Fats (g)"]          = df1["nutritions"].apply(lambda x: x.get("Fat", "0").split()[0])
df1["Free Sugar (g)"]    = df1["nutritions"].apply(lambda x: x.get("Sugar", "0").split()[0])
df1["Fibre (g)"]         = df1["nutritions"].apply(lambda x: x.get("Fiber", "0").split()[0])
df1["Sodium (mg)"]       = df1["nutritions"].apply(lambda x: x.get("Sodium", "0").split()[0])
df1["Calcium (mg)"]      = df1["nutritions"].apply(lambda x: x.get("Calcium", "0").split()[0])
df1["Iron (mg)"]         = df1["nutritions"].apply(lambda x: x.get("Iron", "0").split()[0])
df1["Vitamin C (mg)"]    = df1["nutritions"].apply(lambda x: x.get("Vitamin C", "0").split()[0])

In [56]:
df1  = df1.iloc[:,9:]

In [57]:
df["Category"] =  df["Category"].str.split("/").str.get(0).str.strip()

In [58]:
df.drop(columns=["Notes / Status","Folate (µg)","Category"],inplace=True)

In [59]:
df.head(2)

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg)
0,Halwa Puri,420,52.0,7.0,20.0,8.0,2.1,380,45,1.8,1.2
1,Nihari,310,8.0,28.0,19.0,0.5,0.8,620,42,3.8,5.0

In [60]:
df1.tail(2)

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg)
119,White Chicken Korma,267,8,14,20,3,2,79,72,3,4
120,White Chicken Karahi,531,5,24,45,3,1,136,110,2,3

In [61]:
df2["Dish Name"]

0                                    Hot tea (Garam Chai)
1                                          Instant coffee
2                                          Espreso coffee
3                                                Iced tea
4                             Raw mango drink (Aam panna)
5                         Fruit Punch (with fresh juices)
6                             Fruit Punch (with squashes)
7                                                Lemonade
8                                               Lem-o-gin
9               Cumin infused water (Jeere/Zeere ka pani)
10                                       Coco pine cooler
11                                          Summer cooler
12                                              Hot cocoa
13                             Cold coffee with ice cream
14                      Banana milkshake (Kele milkshake)
15                        Mango milkshake (Aam milkshake)
16                 Pineapple milkshake (Ananas milkshake)
17                   Orange milkshake (Narangi milkshake)
18                                                Egg nog
19                             Sweet Lassi (Meethi lassi)
20                                         Lassi (salted)
21                            Cheese and chilli sandwich
22                        Egg sandwich (Ande ka sandwich)
23                 Cucumber sandwich (Kheere ka sandwich)
24      Cheese and pineapple sandwich (Cheese aur anan...
25      Cheese and tomato sandwich (Cheese aur tamatar...
26                                       Chicken sandwich
27      Peanut and tomato sandwich (Moongfali aur tama...
28                                       Rainbow sandwich
29                                         Club sandwich
30                               Vegetarian club sandwich
31                                     Pin wheel sandwich
32      Carrot apple sandwich (Gajar aur seb ka sandwich)
33                                        Salami sandwich
34                      Vegetable and mayonnaise sandwich
35      Egg and tomato sandwich (Ande aur tamatar ka s...
36                                    Sweet open sandwich
37                 Mushroom and cheese sandwich (toasted)
38      Cheese and tomato sandwich (toasted) (Cheese a...
39      Pea potato sandwich (toasted) (Matar aloo ka s...
40      Paneer pea sandwich (toasted) (Paneer matar ka...
41                             Chicken sandwich (toasted)
42      Pea keema sandwich (toasted) (Matar aur keema ...
43                                  Classic club sandwich
44                                           Sesame toast
45                 Cracked wheat porridge (Meetha daliya)
46                   Semolina porridge (Suji/Rava daliya)
47                                       Oatmeal Porridge
48                                   Cornflakes with milk
49                              Rice flakes (Chiwda/Aval)
50                                           Wheat flakes
51                                  Murmura (Puffed rice)
52                           Puffed wheat (Murmure/Moori)
53                                 Boiled egg (Ubla anda)
54                                             Fried Egg
55                                            Poached egg
56                         Scrambled egg (Ande ki bhurji)
57                                             Baked egg
58                                   Plain omelette/omlet
59                             Stuffed egg omelette/omlet
60                                                Pancake
61                                          Keema pancake
62                                      Vegetable pancake
63                                  Jam and fruit pancake
64                               Khoa and coconut pancake
65                                            Brown stock
66                                        Vegetable stock
67                                          Chicken stock
68                    Clear tomato soup (Tamatar ka soup)
69                                            Lentil soup
70                  Chicken consomme (Clear chicken soup)
71                                   Cream of tomato soup
72                               Cream of green peas soup
73                                  Cream of spinach soup
74                          Cream of mixed vegetable soup
75                                 Cream of mushroom soup
76                                Chicken sweet corn soup
77                                        Minestrone soup
78                                          Egg drop soup
79                     Chinese cabbage and meat ball soup
80                                      French onion soup
81                                      Hot and sour soup
82                                         Talaumein soup
83             Cold cucumber soup (Thanda kheere ka soup)
84                                Cold summer garden soup
85                                           Chapati/Roti
86                                 Plain parantha/paratha
87      Potato parantha/paratha (Aloo ka parantha/para...
88      Radish parantha/paratha (Mooli ka parantha/par...
89      Cauliflower parantha/paratha (Phoolgobhi ka pa...
90                                   Dal parantha/paratha
91                        Sprouted moong parantha/paratha
92       Pea parantha/paratha (Matar ka parantha/paratha)
93                                 Keema parantha/paratha
94                                Paneer parantha/paratha
95      Besan and spinach parantha/paratha (Besan aur ...
96                                                  Poori
97                            Spinach poori (Palak poori)
98                                            Methi poori
99                                      Dal stuffed poori
100                  Potato stuffed poori (Aloo ki poori)
101                             Tandoori parantha/paratha
102                             Boiled rice (Uble chawal)
103                                           Plain pulao
104                                 Mixed vegetable pulao
105                                        Mushroom pulao
106                                  Sprouted moong pulao
107                                          Paneer pulao
108                                         Peanut pulao
109                                        Navratan pulao
110     Green chickpeas pulao (Choliya pulao/Hare chan...
111                               Mutton biryani/biriyani
112                            Vegetable biryani/biriyani
113     Lemon rice (Pulihora, Elumichai sadam, Chitranna)
114                            Sweet rice (Meethe chawal)
115     Curd rice (Dahi bhaat/Dahi chawal/ Perugu anna...
116     Tamarind rice (Chintapandu pulihora/Puliyodhar...
117                                          Spanish rice
118                                    Chinese fried rice
119                                    Macroni cheese pie
120                                    Vegetable chowmein
121                                      Chicken chowmein
122                                    Cheese noodle ring
123            Spaghetti and cheese balls in tomato sauce
124                                         Penne platter
125                                         Pasta hot pot
126                                       Chicken lasagne
127                         Fettuccine with spinach sauce
128                                                  Naan
129                                               Bhatura
130                                                  Idli
131                                           Masala dosa
132                        Semolina dosa (Suji/Rava dosa)
133                                  Onion tomato uttapam
134                                    Paneer kaathi roll
135                                         Makki ki roti
136                 Washed moong dal (Dhuli moong ki dal)
137                   Washed urad dal (Dhuli urad ki dal)
138     Split bengal gram with bottle gourd (Channa da...
139                                       Dry washed urad
140                                             Mixed dal
141                            Whole moong (Moong ki dal)
142                          Whole masoor (Masoor ki dal)
143                              Whole moth (Moth ki dal)
144                              Whole urad (Urad ki dal)
145                  Moti mahal dal (Urad rajmah mix dal)
146     Black channa curry/Bengal gram curry (Kale cha...
147                  Chickpeas curry (Safed channa curry)
148                                           Lobia curry
149                                        Soyabean curry
150                      Kidney bean curry (Rajmah curry)
151                                                Sambar
152                             Besan kadhi with pakodies
153                                         Khatta channa
154                               Sprouted moong dal chat
155                       Potato cauliflower (Aloo gobhi)
156                   Potato capsicum (Shimla mirch aloo)
157               Cabbage and peas (Pattagobhi aur matar)
158             Carrot and fenugreek leaves (Gajar methi)
159                         Potato fenugreek (Aloo methi)
160                  Brinjal bhartha (Baingan ka bhartha)
161                              Dry potato (Sookhe aloo)
162     Beans with coconut (Nariyal aur sem/phali; Bea...
163     Cauliflower with coconut (Nariyal ke saath pho...
164     Carrot and cabbage with coconut (Nariyal ke sa...
165                              Raw turnip with coconut
166               Raw papaya with coconut (Papaya thoran)
167                          Stuffed okra (Bharwa bhindi)
168                    Stuffed round gourd (Bharwa tinde)
169                Stuffed capsicum (Bharwa shimla mirch)
170                      Stuffed brinjal (Bharwa baingan)
171                     Stuffed tomatoes (Bharwa tamatar)
172                         Pea potato curry (Aloo matar)
173                       Pea paneer curry (Matar paneer)
174                   Pea mushroom curry (Matar mushroom)
175                            Pea curry (Matar ki sabzi)
176                                        Pea vadi curry
177                                          Paneer curry
178                  Lotus stem curry (Kamal kakdi curry)
179                                       Gravy for kofta
180                   Pea kofta curry (Matar kofta curry)
181               Spinach kofta curry (Palak kofta curry)
182                                    Paneer kofta curry
183      Lotus stem kofta curry (Kamal kakdi kofta curry)
184             Raw banana kofta curry (Kela kofta curry)
185      Cauliflower kofta curry (Phoolgobhi kofta curry)
186          Cabbage kofta curry (Pattagobhi kofta curry)
187                               Ghiya/Lauki Kofta Curry
188     Spinach paneer kofta curry (Palak paneer kofta...
189                            Vegetarian egg kofta curry
190                                      Baked vegetables
191            Cauliflower musallam (Phoolgobhi musallam)
192                        Baked vegetables with spinach
193                               Baked potato with skin
194                           Shepherd's pie (vegetarian)
195                         Baked brinjal in tomato sauce
196                                              Dum aloo
197                         Spinach paneer (Palak paneer)
198                                          Methi chaman
199                                        Sarson ka saag
200                     Jackfruit sabzi (Kathal ki sabzi)
201                                                 Avial
202                                            Al yakhani
203                                          Shahi paneer
204                                Paneer in butter sauce
205                                    Methi malai paneer
206                                         Chilli paneer
207                                  Paneer makhana korma
208                                         Kadhai Paneer
209                                           Roghan josh
210                         Spinach mutton (Palak mutton)
211                Pea keema curry (Matar keema ki sabzi)
212                                     Keema kofta curry
213                     Kashmiri mutton koftas (Gushtaba)
214                                         Mutton yakhni
215                                        Chicken yakhni
216                                       Mutton do piaza
217                                          Mutton chops
218                                          Shammi kebab
219                                            Scotch egg
220                     Shepherd's pie (with minced meat)
221                                         Chicken curry
222                                      Tandoori chicken
223                                        Butter chicken
224                                         Chicken kebab
225                                        Chilli chicken
226     Fried chicken with tomato sauce (Fried chicken...
227                             Fish curry (Machli curry)
228           Fried fish (Indian style) (Tali hui machli)
229     Fried fish and Chips (English Style) (Tali hui...
230                                           Tomato fish
231                          Baked fish with cheese sauce
232                                            Fish tikka
233                                         Tandoori fish
234                     Paneer, apple and pineapple salad
235                                         Russian salad
236                                           Pasta salad
237                                           Deviled egg
238                                          Hawain salad
239                       Mixed pulse and vegetable salad
240                                 Sprouted moong salad
241                                          Tossed salad
242                 Mixed vegetable salad with curd sauce
243                         Potato salad (Aloo ka salaad)
244                                        Waldroff salad
245                                              Coleslaw
246                        Fruit salad (Phalon ka salaad)
247       Tomato onion raita (Tamatar aur pyaaz ka raita)
248                      Peanut raita (Mungfali ka raita)
249                                 Sprouted moong raita
250             Bottle gourd raita (Ghiya/Lauki ka raita)
251                      Cucumber raita (Kheere ka raita)
252     Carrot and spinach raita (Gajar aur palak ka r...
253                         Mint raita (Pudinay ka raita)
254                          Potato raita (Aloo ka raita)
255                                          Boondi raita
256                            Sweet raita (Meetha raita)
257                                Dahi vadas/Dahi bhalla
258                                                Gunjia
259               Saunth/Sonth chutney with tamarind/imli
260                          Rice kheer (Chawal ki kheer)
261                                         Makhana kheer
262            Vermicelli kheer (Semiya/Seviyan ki kheer)
263                      Semolina kheer (Suji/Rava kheer)
264                                          Paneer kheer
265                   Cabbage kheer (Pattagobhi ki kheer)
266                         Carrot kheer (Gajar ki kheer)
267               Cauliflower kheer (Phoolgobhi ki kheer)
268                                       Moong dal kheer
269                                                Phirni
270                        Semolina halwa (Suji ka halwa)
271                                      Shahi suji halwa
272                         Carrot halwa (Gajar ka halwa)
273                             Egg halwa (Ande ka halwa)
274                          Potato halwa (Aloo ka halwa)
275                        Pumpkin halwa (Kaddu ka halwa)
276                                       Moong dal halwa
277                             Caramel custard (steamed)
278                                         Baked custard
279                                Soft Custard (stirred)
280                                   Chocolate ice cream
281                                       Mango ice cream
282                 Fruit Ice cream (Phalon ka Ice cream)
283                                     Caramel ice cream
284                                         Lemon souffle
285                                        Orange souffle
286                                       Vanilla souffle
287                                     Chocolate souffle
288                                    Pineapple souffle
289                                          Apple mousse
290                                 Rich chocolate mousse
291                                          Mango mousse
292                            Orange and pineapple cream
293                                      Charlotte rousse
294                                       Triffle pudding
295                                   Snow flakes pudding
296                                                 Kulfi
297                                Steamed orange pudding
298                             Meringue and rice pudding
299                                        Cheese pudding
300                                     Chocolate pudding
301                             Bread and butter pudding
302                                      Queen of pudding
303                         Pineapple upside down pudding
304                                      Date and nut pie
305                             Stewed apple with custard
306                                       Apple snowballs
307                                    Hot orange souffle
308                                 Hot chocolate souffle
309                                   Hot vanilla souffle
310                                   Plain burfi (Burfi)
311                      Coconut burfi (Nariyal ki burfi)
312                Bottle gourd burfi (Ghiya/Lauki burfi)
313                                       Chocolate burfi
314               Cashewnut burfi (Kaju burfi/Kaju katli)
315                        Gram flour burfi (Besan burfi)
316     Semolina ladoo with khoya (Suji/Rava aur khoye...
317     Semolina ladoo with coconut (Suji/Rava aur nar...
318                        Gram flour ladoo (Besan ladoo)
319                           Sesame ladoo (Til ke ladoo)
320                                          Chenna murki
321                                             Milk cake
322                                  Ghujia/Lavang latika
323                                Gulab Jamun with khoya
324                                               Mal pua
325                                           Shahi tukre
326                    Potato pakora/pakoda (Aloo pakoda)
327                 Onion pakora/pakoda (Pyaaz ke pakode)
328      Cauliflower pakora/pakoda (Phoolgobhi ke pakode)
329                         Mixed vegetable pakora/pakoda
330                  Spinach pakora/pakoda (Palak pakoda)
331                 Methi pakora/pakoda (Methi ke pakode)
332                    Egg pakora/pakoda (Ande ke pakode)
333                                   Bread pakora/pakoda
334                                  Paneer pakora/pakoda
335                             Potato bonda (Aloo bonda)
336                        Potato samosa (Aloo ka samosa)
337                  Minced meat samosa (Keema ka samosa)
338        Paneer and pea samosa (Paneer matar ka samosa)
339                                                Mathri
340                                        Khasta kachori
341                                      Vegetable cutlet
342     Flattened rice cutlet (Chirwa cutlet/Chivda cu...
343                    Peanut cutlet (Mungfali ke cutlet)
344                        Fish cutlet (Machli ka cutlet)

In [62]:
south_indian = [
    "Idli", "Masala dosa", "Plain dosa", "Semolina dosa (Suji/Rava dosa)",
    "Onion tomato uttapam", "Uttapam", "Appam", "Banana appam",
    "Sambar", "Rasam with tamarind", "Rasam with lemon", "Rasam powder (Rasam masala)",
    "Sambar powder (Sambar masala)", "Semolina idli (Suji/Rava idli)",
    "Instant idli (with semolina)", "Moong bean dosa (Pesarattu)", "Jowar dosa",
    "Rice puttu (Ari puttu)", "Avial", "Beans foogath", "Beans with coconut",
    "Cauliflower with coconut", "Carrot and cabbage with coconut",
    "Raw papaya with coconut", "Fish in coconut milk", "Prawn curry (with coconut)",
    "Kesari bath", "Putharekulu", "Rice murukku", "Sev (Omapodi/Karapusa)",
    "Dalma", "Gobi 65", "Gun powder chutney", "Tamarind rice",
    "Eggplant/Brinjal rice (Vangi bhat)", "Curd rice", "Lemon rice",
    "Bengal 5 Spice Blend (Panch Phoran)", "Black rice kheer (Chak-hao kheer)",
    "Nannari sharbat", "Woodapple juice (Bel ka sharbat)", "Thari kanji"
]

gujarati = [
    "Dhokla", "Khaman (dhokla)", "Instant dhokla", "Gram flour and semolina dhokla",
    "Semolina dhokla (Suji/Rava dhokla)", "Gujarati handvo", "Methi thepla",
    "Khakhra", "Khakhra chaat", "Dal dhokli", "Dhansak (vegetarian)",
    "Pav bhaji", "Pav bhaji masala", "Bhel puri", "Papdi",
    "Sago khitchdi", "Peanut sago vada", "Sago cutlet/vadas",
    "Methi thepla", "Soyabean muthias"
]
bengali = [
    "Dil bahar", "Rasbhari",
    "Rajbogh", "Chhena poda", "Chenna murki", "Danedar burfi",
    "Bengal fish curry (Bengali machli curry)", "Kashmiri mutton koftas (Gushtaba)",
    "Buckwheat pancake (Khura)", "Fermented bamboo shoot pickle",
    "Pickled mustard greens", "Dalma"
]
western = [
    "Bacon and mushroom pancake", "Ham and Bean soup", "Salami sandwich",
    "Danish luncheon sandwich", "Shepherd's pie (vegetarian)",
    "Shepherd's pie (with minced meat)", "Lasagne with meat sauce",
    "Lasagne with vegetables", "Chicken lasagne", "Spaghetti bolognese",
    "Fettuccine with spinach sauce", "Classic italian pasta",
    "Macaroni salad", "Macroni cheese pie", "Beans and macaroni",
    "Meat and macaroni casserole", "Charlotte rousse", "Pavlova",
    "Dundee cake", "Christmas cake", "Christmas biscuit",
    "Christmas wreath biscuit", "Christmas bell biscuit",
    "Christmas star biscuit", "Christmas tree biscuit",
    "Black forest gateau", "Black forest pastry", "Lemon chiffon pie",
    "Orange chiffon pie", "Chocolate meringue pie", "Lemon meringue pie",
    "Peach melba ice cream", "Coffee pear alaska", "Raspberry bavarian cream",
    "Jellied sunshine fruit salad", "Tomato aspic", "Consomme au julienne",
    "Consomme au vermicelli", "Mulligatawny soup", "French onion soup",
    "Vichyssoise", "Charlotte rousse", "Choux swans", "Cream horns",
    "Savoury cheese horns", "Potato aigrettes", "Sweet couscous dessert"
]


removed_food  = western+ bengali + gujarati+ south_indian

df2 = df2[~df2["Dish Name"].isin(removed_food)].reset_index(drop=True)
len(df2)

917

In [63]:
df2.head(4)

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.0,3.12,14.20,0.02,0.50,1.80
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.0,4.92,20.87,0.06,1.51,5.60
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.0,13.98,58.10,0.15,1.51,5.53
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.0,0.23,1.18,0.02,5.95,1.28

In [64]:
a = df2[df2["Dish Name"].str.contains("sandwich")]
x  = df2[df2["Dish Name"].str.contains("sandwich")]["Dish Name"].str.split("sandwich").str.get(0).str.strip()
df2.loc[a.index,"Dish Name"] = x + " sandwich"

In [65]:
df2[df2["Dish Name"].str.contains("sandwich")].head(2)

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg)
21,Cheese and chilli sandwich,218.11,27.40,6.80,9.78,2.38,2.08,437.50,113.79,0.99,12.3,16.14
22,Egg sandwich,285.96,29.16,8.69,15.80,1.86,1.88,461.67,110.13,1.44,0.0,14.92

In [66]:
df2  = df2[~df2["Dish Name"].str.contains("seeds")]
df2["Dish Name"]  = df2["Dish Name"].str.split("(").str.get(0).str.strip().str.split(")").str.get(0).str.strip()

In [67]:
df2.drop(columns="Folate (µg)",inplace=True)

In [68]:
df = pd.concat([df, df1, df2], ignore_index=True)

In [69]:
df.to_csv("../data/Cleaned Nutrients.csv")